"""Render the PyScope HTML dashboard (Observatory dark theme)."""

from __future__ import annotations

import os
import hashlib
import datetime
from typing import Dict, Optional

from .schema import C1Result

HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>PyScope Observation \u2014 {repository}</title>
<style>
  :root {{
    --bg: #0A0E17;
    --card: #111827;
    --card-hover: #1F2937;
    --border: #1E293B;
    --fg: #F1F5F9;
    --muted: #94A3B8;
    --accent: #38BDF8;
    --success: #22C55E;
    --warn: #F59E0B;
    --danger: #EF4444;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: var(--bg);
    color: var(--fg);
    font-family: ui-sans-serif, system-ui, -apple-system, sans-serif;
    line-height: 1.6;
    min-height: 100vh;
    padding: 2rem 1rem;
  }}
  .container {{ max-width: 1280px; margin: 0 auto; }}
  header {{
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 1.75rem;
    margin-bottom: 1.5rem;
  }}
  header h1 {{
    font-family: ui-monospace, 'SF Mono', Consolas, monospace;
    font-size: 1.75rem;
    color: var(--accent);
    margin-bottom: 0.5rem;
  }}
  header .meta {{
    color: var(--muted);
    font-size: 0.875rem;
    display: flex;
    gap: 1.5rem;
    flex-wrap: wrap;
  }}
  header .meta span strong {{ color: var(--fg); }}
  .grid {{
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
    gap: 1rem;
    margin-bottom: 1.5rem;
  }}
  .card {{
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 1.25rem;
    transition: transform 0.15s ease, box-shadow 0.15s ease, background 0.15s ease;
  }}
  .card:hover {{
    background: var(--card-hover);
    transform: translateY(-2px);
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
  }}
  .card .label {{
    color: var(--muted);
    font-size: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    margin-bottom: 0.5rem;
  }}
  .card .value {{
    font-family: ui-monospace, 'SF Mono', Consolas, monospace;
    font-size: 1.5rem;
    font-weight: 600;
    color: var(--fg);
  }}
  .card .value.accent {{ color: var(--accent); }}
  .card .value.success {{ color: var(--success); }}
  .card .value.warn {{ color: var(--warn); }}
  .card .value.danger {{ color: var(--danger); }}
  .graph-container {{
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 1.5rem;
    margin-bottom: 1.5rem;
    overflow: auto;
  }}
  .graph-container h2 {{
    font-size: 0.875rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--muted);
    margin-bottom: 1rem;
  }}
  .graph-container svg {{
    max-width: 100%;
    height: auto;
    display: block;
  }}
  .legend {{
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 1.25rem;
    margin-bottom: 1.5rem;
  }}
  .legend h2 {{
    font-size: 0.875rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--muted);
    margin-bottom: 1rem;
  }}
  .legend-grid {{
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
    gap: 0.5rem;
  }}
  .legend-item {{
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.5rem;
    border-radius: 6px;
    background: var(--bg);
  }}
  .swatch {{
    width: 14px; height: 14px;
    border-radius: 3px;
    flex-shrink: 0;
    border: 1px solid var(--border);
  }}
  .legend-item code {{
    font-family: ui-monospace, 'SF Mono', Consolas, monospace;
    font-size: 0.75rem;
    color: var(--fg);
  }}
  footer {{
    text-align: center;
    color: var(--muted);
    font-size: 0.75rem;
    padding: 1.5rem 0;
    border-top: 1px solid var(--border);
    margin-top: 2rem;
  }}
  footer code {{
    font-family: ui-monospace, 'SF Mono', Consolas, monospace;
    color: var(--accent);
  }}
</style>
</head>
<body>
  <div class="container">
    <header>
      <h1>PyScope Observation</h1>
      <div class="meta">
        <span><strong>Repository:</strong> {repository}</span>
        <span><strong>Observed:</strong> {observed_at}</span>
        <span><strong>Nodes:</strong> {num_nodes}</span>
        <span><strong>Edges:</strong> {num_edges}</span>
      </div>
    </header>

    <div class="grid">
      {metric_cards}
    </div>

    <div class="graph-container">
      <h2>Architectural Graph</h2>
      {svg_content}
    </div>

    <div class="legend">
      <h2>Regime Color Legend</h2>
      <div class="legend-grid">
        {legend_items}
      </div>
    </div>

    <footer>
      Generated by <code>PyScope</code> \u00b7 {generated_at} \u00b7 hash <code>{file_hash}</code>
    </footer>
  </div>
</body>
</html>
"""

METRIC_LABELS = {
    "cross_domain_ratio": ("Cross-Domain Ratio", "accent"),
    "intra_domain_ratio": ("Intra-Domain Ratio", ""),
    "leakage": ("Boundary Leakage", "warn"),
    "cycle_density": ("Cycle Density", "warn"),
    "observation_quality": ("Observation Quality", "success"),
    "total_nodes": ("Total Nodes", ""),
    "total_edges": ("Total Edges", ""),
    "cross_domain_edges": ("Cross-Domain Edges", "accent"),
    "intra_domain_edges": ("Intra-Domain Edges", ""),
    "unknown_unresolved_edges": ("Unresolved Edges", "warn"),
    "unknown_dynamic_edges": ("Dynamic Edges", "warn"),
    "regime": ("Detected Regime", "success"),
    "distance_1": ("Distance to Nearest", "warn"),
    "margin": ("Classification Margin", "success"),
    "confidence": ("Classification Confidence", "success"),
    "nearest_regime": ("Nearest Regime", "accent"),
    "second_nearest_regime": ("Second Nearest", ""),
}

REGIME_COLORS = {
    "perfect": "#22C55E",
    "modular_small": "#38BDF8",
    "modular_large": "#38BDF8",
    "layered": "#60A5FA",
    "entangled_small": "#F59E0B",
    "entangled_large": "#F59E0B",
    "coupled": "#EF4444",
    "leaky": "#EC4899",
    "collapsed": "#991B1B",
    "mixed": "#A78BFA",
    "pathological": "#7C2D12",
    "acyclic_dominant": "#67E8F9",
}


def _format_value(v) -> str:
    if isinstance(v, float):
        return f"{v:.3f}"
    return str(v)


def _metric_card(key: str, value) -> str:
    label, css_class = METRIC_LABELS.get(key, (key.replace("_", " ").title(), "accent"))
    cls_attr = f' class="value {css_class}"' if css_class else ' class="value"'
    return (
        f'<div class="card">'
        f'<div class="label">{label}</div>'
        f'<div{cls_attr}>{_format_value(value)}</div>'
        f'</div>'
    )


def _legend_item(label: str, color: str) -> str:
    return (
        f'<div class="legend-item">'
        f'<div class="swatch" style="background: {color};"></div>'
        f'<code>{label}</code>'
        f'</div>'
    )


def write_html_report(
    output_dir: str,
    artifacts: Dict[str, str],
    metrics: dict,
) -> str:
    """Render the PyScope dashboard HTML to ``<output_dir>/index.html``.

    *artifacts* must contain ``"svg"`` with the path to the rendered SVG.
    *metrics* is the dictionary of metrics/regime info to render as cards.
    """
    os.makedirs(output_dir, exist_ok=True)
    html_path = os.path.join(output_dir, "index.html")

    svg_content = ""
    svg_path = artifacts.get("svg", "")
    if svg_path and os.path.exists(svg_path):
        try:
            with open(svg_path, "r", encoding="utf-8") as f:
                svg_content = f.read()
        except OSError:
            svg_content = '<p style="color: var(--danger);">SVG unavailable</p>'

    metric_cards = "\n".join(_metric_card(k, v) for k, v in metrics.items())
    legend_items = "\n".join(
        _legend_item(label, color) for label, color in REGIME_COLORS.items()
    )

    repository = metrics.get("repository", "unknown")
    observed_at = metrics.get("observed_at", "unknown")
    num_nodes = metrics.get("total_nodes", len(artifacts.get("nodes", [])))
    num_edges = metrics.get("total_edges", len(artifacts.get("edges", [])))

    generated_at = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    file_hash = hashlib.sha256(svg_content.encode("utf-8")).hexdigest()[:12]

    html = HTML_TEMPLATE.format(
        repository=repository,
        observed_at=observed_at,
        num_nodes=num_nodes,
        num_edges=num_edges,
        metric_cards=metric_cards,
        svg_content=svg_content,
        legend_items=legend_items,
        generated_at=generated_at,
        file_hash=file_hash,
    )

    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html)

    return html_path


def write_report_from_c1(
    output_dir: str,
    c1: C1Result,
    svg_path: Optional[str] = None,
) -> str:
    """Convenience: build the dashboard directly from a ``C1Result``."""
    metrics = dict(c1.metrics or {})
    metrics.setdefault("repository", c1.repository or "unknown")
    metrics.setdefault("observed_at", c1.observed_at or "unknown")
    metrics.setdefault("total_nodes", len(c1.nodes))
    metrics.setdefault("total_edges", len(c1.edges))

    artifacts: Dict[str, str] = {"nodes": [n.id for n in c1.nodes]}
    if svg_path:
        artifacts["svg"] = svg_path
    return write_html_report(output_dir, artifacts, metrics)
